### ISSUE TITLE
Example of using in NodeJS

### ISSUE THREAD

**Issue by mseminatore** [gf3/Levenshtein#20]
I am having some trouble figuring out how to incorporate this into my NodeJS app.  I've `npm installed levenshtein` in my app.

var Levenshtein = require('levenshtein');
var dist = new Levenshtein('foo', 'bar').distance; // Levenshtein is not defined

**Comment by gf3** [comment]
hey @mseminatore seems to work for me using the code/steps you provided:

![screen recording](https://d3vv6lp55qjaqc.cloudfront.net/items/2L213r1h0v0M112G280L/Screen%20Recording%202017-02-21%20at%2001.58%20PM.gif?X-CloudApp-Visitor-Id=99251)

**Comment by mseminatore** [comment]
@gf3 Which node version are you using?  I was using a very old version (0.10.36).  I retried using LTS of 6.10.0 and it worked.  You may want to update the docs to be clear on min supported Node version.

**Comment by gf3** [comment]
yeah i was definitely using a recent node. so strange

**Comment by mseminatore** [comment]
No worries!  I shouldn't have been using such an old version.  Nice library!
